import streamlit as st
import requests

#uses a 3 state finite machine with phases stored in st.session state and then communicates with the backend via http
# then tracks the active thread_id across re-renders using Streamlit's session storage



# configure the api url. it should match the uvicorn server
API_URL = "http://localhost:8000/api"

st.set_page_config(page_title="Smart Grid AI Copilot", layout="centered")

# initialize session state

#tracking the current state of the UI workflow
if "status" not in st.session_state:
    st.session_state.status = "idle"  # states: idle, pending_approval, completed

#stores the UUD generated by the backend for the current incident
if "thread_id" not in st.session_state:
    st.session_state.thread_id = None

#stores the proposed plan produced by the agent when execution pauses at HITL breakup
if "drafted_action" not in st.session_state:
    st.session_state.drafted_action = ""

#storing the final outcome message
if "final_message" not in st.session_state:
    st.session_state.final_message = ""

# UI header
st.title("Smart Grid AI Copilot")
st.markdown("Automated Incident Triage & Resolution Agent")
st.divider()

# phase 1: trigger the incident 
if st.session_state.status == "idle":
    st.subheader("New Grid Alert")
    
    default_alert = (
        "Electricity spot prices dropped to negative values recently. "
        "Please query the historical prices from 2024-03-01 to 2024-03-05 and PROPOSE ACTION."
    )
    #make a multi line text input allowing the operator to modify or enter incident details
    alert_text = st.text_area("Incident Details", value=default_alert, height=100)
    
    if st.button("Investigate Incident", type="primary"):
        with st.spinner("Agent is investigating logs and data..."):
            try:

                #send a POST request to start the investigation on the fast api server
                response = requests.post(f"{API_URL}/investigate", json={"alert_text": alert_text})
                response.raise_for_status()
                data = response.json()

                #save the returned incident threadID and workflow status to session state
                st.session_state.thread_id = data.get("thread_id")
                st.session_state.status = data.get("status")

                #check whether the backend halted at approval gate or completed directly
                if st.session_state.status == "pending_approval":
                    st.session_state.drafted_action = data.get("drafted_action")
                else:
                    st.session_state.final_message = data.get("message")
                
                st.rerun()
            except Exception as e:
                st.error(f"Backend API Error: Ensure Uvicorn is running and your API key is set. Details: {e}")

#phase 2: human in loop approval
elif st.session_state.status == "pending_approval":
    st.warning("⏸️ Execution Paused: Human Approval Required")
    
    st.markdown("### Agent's Findings & Proposed Action")
    #display the drafted resolution plan recieved from the agent in an info box
    st.info(st.session_state.drafted_action)
    
    st.markdown("Do you approve executing this action?")

    #for side by side buttons
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button(" Approve Action", use_container_width=True):
            with st.spinner("Executing approved action..."):
                res = requests.post(
                    f"{API_URL}/approve/{st.session_state.thread_id}", 
                    json={"approved": True}
                )
                st.session_state.status = "completed"
                st.session_state.final_message = res.json().get("final_message")
                st.rerun()
                
    with col2:
        if st.button("Reject Action", use_container_width=True):
            with st.spinner("Cancelling workflow..."):
                res = requests.post(
                    f"{API_URL}/approve/{st.session_state.thread_id}", 
                    json={"approved": False}
                )
                st.session_state.status = "completed"
                st.session_state.final_message = res.json().get("final_message")
                st.rerun()

#WORKFLOW IS NOW DONE
elif st.session_state.status == "completed":
    st.success("Workflow Completed")
    
    st.markdown("### Final System Output")
    #display the final message; either execution summary or abort
    st.code(st.session_state.final_message, language="markdown")


        
    if st.button("Acknowledge & Clear"):
        st.session_state.status = "idle"
        st.session_state.thread_id = None
        st.session_state.drafted_action = ""
        st.session_state.final_message = ""
        st.rerun()